# POST http://localhost:7070/api/list/savelist
# Content-Type: application/json

# {
#     "list": "Rice",
#     "price": 85.00,
#     "quantity": 1,
#     "category": "groceries"
    
# }

 Get http://localhost:7070/api/list/getbudget/3

# DELETE   http://localhost:7070/api/list/deletelist/1

# PUT http://localhost:7070/api/list/updatebudget/1
# Content-Type: application/json

# {
#     "amount": 3000.00,
#     "listId": 1
    
    
# }