# POST http://localhost:7070/api/list/savelist
# Content-Type: application/json

# {
#     "list": "haircut",
#     "price": 50,
#     "quantity": 1,
#     "category": "general"
# }

# Get http://localhost:7070/api/list/getlist

DELETE   http://localhost:7070/api/list/deletelist/1