POST http://localhost:7070/user/signup
Content-Type: application/json

{
    "firstName": "Racheal",
    "lastName": "Kuranchie",
    "email": "racheal2@gmail.com",
    "userName": "richeal20",
    "password": "racheal2023"   
}

# POST http://localhost:7070/user/login
# Content-Type: application/json

# {
#     "email": "racheal@gmail.com",
#     "password": "racheal2023" 
# }

# POST http://localhost:7070/api/list/savelist
# Content-Type: application/json

# {
#     "list": "bag",
#     "price": 100.00, 
#     "quantity": 3,
#     "userId": 2
    
# }

#   Get http://localhost:7070/user/logout

# DELETE   http://localhost:7070/api/list/deletelist/1

# PUT  http://localhost:7070/api/list/updatebudget/1
# Content-Type: application/json

# {
#     "budget": 1000.00   
# }